### ISSUE TITLE
Ready to share? 

### ISSUE THREAD

**Issue by iangilman** [jeremytubbs/deepzoom#2]
Great to see this tool! Are you ready for me to add it to the OpenSeadragon tools list? 

http://openseadragon.github.io/examples/creating-zooming-images/

**Comment by jeremytubbs** [comment]
Yes, I should be moving to a 1.0 soon because I am using this in production now... I need to spend some time thinking about throwing exceptions vs. the json 'error' response. 

Also I need better documentation / testing because it should work the the PHP League Flysystem http://flysystem.thephpleague.com/ and its various filesystem adapters for the likes of AWS and Dropbox but I have only been using the Local adapter.

**Comment by iangilman** [comment]
Awesome. We'll go ahead and add it now...thanks! 

Btw, what site are you using it on? :)

**Comment by iangilman** [comment]
Added: 

http://openseadragon.github.io/examples/creating-zooming-images/

**Comment by jeremytubbs** [comment]
@iangilman Thanks!

**Comment by iangilman** [comment]
Awesome; I look forward to seeing it in action! :-)
